### PR TITLE
Patched synapses added

### PR DESCRIPTION
**Pull request by Faezehabibi**
Patched synapses added

### CODE REVIEW

**Comment by Faezehabibi** [comment]
Patched synapses added, please review.

**Comment by Faezehabibi** [comment]
please accept the last rq only
current rq is pull 2

**Comment by Faezehabibi** [comment]
pull 3

**Comment by Faezehabibi** [comment]
Last one if anything has changed. Also please take care of the RateCell `display_name`

**Review by willgebhardt — APPROVED** [review]

**Comment by Faezehabibi** [comment]
Ive sent the pic to William's discord to check

**Pull request merged**
